
Bookモデルのテスト
  バリデーションのテスト
    titleカラム
      空欄でないこと
    bodyカラム
      空欄でないこと
      200文字以下であること: 200文字は〇
      200文字以下であること: 201文字は×
  アソシエーションのテスト
    Userモデルとの関係
      N:1となっている

Userモデルのテスト
  バリデーションのテスト
    nameカラム
      空欄でないこと
      2文字以上であること: 1文字は×
      2文字以上であること: 2文字は〇
      20文字以下であること: 20文字は〇
      20文字以下であること: 21文字は×
      一意性があること (FAILED - 1)
    introductionカラム
      50文字以下であること: 50文字は〇
      50文字以下であること: 51文字は×
  アソシエーションのテスト
    Bookモデルとの関係
      1:Nとなっている

[STEP1] ユーザログイン前のテスト
  トップ画面のテスト
    表示内容の確認
      URLが正しい
      Log inリンクが表示される: 左上から5番目のリンクが「Log in」である
      Log inリンクの内容が正しい
      Sign Upリンクが表示される: 左上から6番目のリンクが「Sign Up」である
      Sign Upリンクの内容が正しい
  アバウト画面のテスト
    表示内容の確認
      URLが正しい (FAILED - 2)
  ヘッダーのテスト: ログインしていない場合
    表示内容の確認
      タイトルが表示される
      Homeリンクが表示される: 左上から1番目のリンクが「Home」である
      Aboutリンクが表示される: 左上から2番目のリンクが「About」である
      sign upリンクが表示される: 左上から3番目のリンクが「sign up」である
      loginリンクが表示される: 左上から4番目のリンクが「login」である
    リンクの内容を確認
      Homeを押すと、トップ画面に遷移する
      Aboutを押すと、アバウト画面に遷移する (FAILED - 3)
      sign upを押すと、新規登録画面に遷移する
      loginを押すと、ログイン画面に遷移する
  ユーザ新規登録のテスト
    表示内容の確認
      URLが正しい
      「Sign up」と表示される
      nameフォームが表示される
      emailフォームが表示される
      passwordフォームが表示される
      password_confirmationフォームが表示される
      Sign upボタンが表示される
    新規登録成功のテスト
      正しく新規登録される
      新規登録後のリダイレクト先が、新規登録できたユーザの詳細画面になっている
  ユーザログイン
    表示内容の確認
      URLが正しい
      「Log in」と表示される
      nameフォームが表示される (FAILED - 4)
      passwordフォームが表示される
      Sign upボタンが表示される
      emailフォームは表示されない (FAILED - 5)
    ログイン成功のテスト
      ログイン後のリダイレクト先が、ログインしたユーザの詳細画面になっている (FAILED - 6)
    ログイン失敗のテスト
      ログインに失敗し、ログイン画面にリダイレクトされる (FAILED - 7)
  ヘッダーのテスト: ログインしている場合
    ヘッダーの表示を確認
      タイトルが表示される (FAILED - 8)
      Homeリンクが表示される: 左上から1番目のリンクが「Home」である (FAILED - 9)
      Usersリンクが表示される: 左上から2番目のリンクが「Users」である (FAILED - 10)
      Booksリンクが表示される: 左上から3番目のリンクが「Books」である (FAILED - 11)
      log outリンクが表示される: 左上から4番目のリンクが「logout」である (FAILED - 12)
  ユーザログアウトのテスト
    ログアウト機能のテスト
      正しくログアウトできている: ログアウト後のリダイレクト先においてAbout画面へのリンクが存在する (FAILED - 13)
      ログアウト後のリダイレクト先が、トップになっている (FAILED - 14)

[STEP2] ユーザログイン後のテスト
  ヘッダーのテスト: ログインしている場合
    リンクの内容を確認: ※logoutは『ユーザログアウトのテスト』でテスト済みになります。
      Homeを押すと、自分のユーザ詳細画面に遷移する (FAILED - 15)
      Usersを押すと、ユーザ一覧画面に遷移する (FAILED - 16)
      Booksを押すと、投稿一覧画面に遷移する (FAILED - 17)
  投稿一覧画面のテスト
    表示内容の確認
      URLが正しい (FAILED - 18)
      自分と他人の画像のリンク先が正しい (FAILED - 19)
      自分の投稿と他人の投稿のタイトルのリンク先がそれぞれ正しい (FAILED - 20)
      自分の投稿と他人の投稿のオピニオンが表示される (FAILED - 21)
    サイドバーの確認
      自分の名前と紹介文が表示される (FAILED - 22)
      自分のユーザ編集画面へのリンクが存在する (FAILED - 23)
      「New book」と表示される (FAILED - 24)
      titleフォームが表示される (FAILED - 25)
      titleフォームに値が入っていない (FAILED - 26)
      opinionフォームが表示される (FAILED - 27)
      opinionフォームに値が入っていない (FAILED - 28)
      Create Bookボタンが表示される (FAILED - 29)
    投稿成功のテスト
      自分の新しい投稿が正しく保存される (FAILED - 30)
      リダイレクト先が、保存できた投稿の詳細画面になっている (FAILED - 31)
  自分の投稿詳細画面のテスト
    表示内容の確認
      URLが正しい (FAILED - 32)
      「Book detail」と表示される (FAILED - 33)
      ユーザ画像・名前のリンク先が正しい (FAILED - 34)
      投稿のtitleが表示される (FAILED - 35)
      投稿のopinionが表示される (FAILED - 36)
      投稿の編集リンクが表示される (FAILED - 37)
      投稿の削除リンクが表示される (FAILED - 38)
    サイドバーの確認
      自分の名前と紹介文が表示される (FAILED - 39)
      自分のユーザ編集画面へのリンクが存在する (FAILED - 40)
      「New book」と表示される (FAILED - 41)
      titleフォームが表示される (FAILED - 42)
      titleフォームに値が入っていない (FAILED - 43)
      opinionフォームが表示される (FAILED - 44)
      opinionフォームに値が入っていない (FAILED - 45)
      Create Bookボタンが表示される (FAILED - 46)
    投稿成功のテスト
      自分の新しい投稿が正しく保存される (FAILED - 47)
    編集リンクのテスト
      編集画面に遷移する (FAILED - 48)
    削除リンクのテスト
      正しく削除される (FAILED - 49)
      リダイレクト先が、投稿一覧画面になっている (FAILED - 50)
  自分の投稿編集画面のテスト
    表示の確認
      URLが正しい (FAILED - 51)
      「Editing Book」と表示される (FAILED - 52)
      title編集フォームが表示される (FAILED - 53)
      opinion編集フォームが表示される (FAILED - 54)
      Update Bookボタンが表示される (FAILED - 55)
      Showリンクが表示される (FAILED - 56)
      Backリンクが表示される (FAILED - 57)
    編集成功のテスト
      titleが正しく更新される (FAILED - 58)
      bodyが正しく更新される (FAILED - 59)
      リダイレクト先が、更新した投稿の詳細画面になっている (FAILED - 60)
  ユーザ一覧画面のテスト
    表示内容の確認
      URLが正しい (FAILED - 61)
      自分と他人の画像が表示される: fallbackの画像がサイドバーの1つ＋一覧(2人)の2つの計3つ存在する (FAILED - 62)
      自分と他人の名前がそれぞれ表示される (FAILED - 63)
      自分と他人のshowリンクがそれぞれ表示される (FAILED - 64)
    サイドバーの確認
      自分の名前と紹介文が表示される (FAILED - 65)
      自分のユーザ編集画面へのリンクが存在する (FAILED - 66)
      「New book」と表示される (FAILED - 67)
      titleフォームが表示される (FAILED - 68)
      titleフォームに値が入っていない (FAILED - 69)
      opinionフォームが表示される (FAILED - 70)
      opinionフォームに値が入っていない (FAILED - 71)
      Create Bookボタンが表示される (FAILED - 72)
  自分のユーザ詳細画面のテスト
    表示の確認
      URLが正しい (FAILED - 73)
      投稿一覧のユーザ画像のリンク先が正しい (FAILED - 74)
      投稿一覧に自分の投稿のtitleが表示され、リンクが正しい (FAILED - 75)
      投稿一覧に自分の投稿のopinionが表示される (FAILED - 76)
      他人の投稿は表示されない (FAILED - 77)
    サイドバーの確認
      自分の名前と紹介文が表示される (FAILED - 78)
      自分のユーザ編集画面へのリンクが存在する (FAILED - 79)
      「New book」と表示される (FAILED - 80)
      titleフォームが表示される (FAILED - 81)
      titleフォームに値が入っていない (FAILED - 82)
      opinionフォームが表示される (FAILED - 83)
      opinionフォームに値が入っていない (FAILED - 84)
      Create Bookボタンが表示される (FAILED - 85)
  自分のユーザ情報編集画面のテスト
    表示の確認
      URLが正しい (FAILED - 86)
      名前編集フォームに自分の名前が表示される (FAILED - 87)
      画像編集フォームが表示される (FAILED - 88)
      自己紹介編集フォームに自分の自己紹介文が表示される (FAILED - 89)
      Update Userボタンが表示される (FAILED - 90)
    更新成功のテスト
      nameが正しく更新される (FAILED - 91)
      introductionが正しく更新される (FAILED - 92)
      リダイレクト先が、自分のユーザ詳細画面になっている (FAILED - 93)

[STEP3] 仕上げのテスト
  サクセスメッセージのテスト
    ユーザ新規登録成功時
    ユーザログイン成功時 (FAILED - 94)
    ユーザログアウト成功時 (FAILED - 95)
    ユーザのプロフィール情報更新成功時 (FAILED - 96)
    投稿データの新規投稿成功時: 投稿一覧画面から行います。 (FAILED - 97)
    投稿データの更新成功時 (FAILED - 98)
  処理失敗時のテスト
    ユーザ新規登録失敗: nameを1文字にする
      新規登録されない
      新規登録画面を表示しており、フォームの内容が正しい
      バリデーションエラーが表示される
    ユーザのプロフィール情報編集失敗: nameを1文字にする
      更新されない (FAILED - 99)
      ユーザ編集画面を表示しており、フォームの内容が正しい (FAILED - 100)
      バリデーションエラーが表示される (FAILED - 101)
    投稿データの新規投稿失敗: 投稿一覧画面から行い、titleを空にする
      投稿が保存されない (FAILED - 102)
      投稿一覧画面を表示している (FAILED - 103)
      新規投稿フォームの内容が正しい (FAILED - 104)
      バリデーションエラーが表示される (FAILED - 105)
    投稿データの更新失敗: titleを空にする
      投稿が更新されない (FAILED - 106)
      投稿編集画面を表示しており、フォームの内容が正しい (FAILED - 107)
      エラーメッセージが表示される (FAILED - 108)
  ログインしていない場合のアクセス制限のテスト: アクセスできず、ログイン画面に遷移する
    ユーザ一覧画面
    ユーザ詳細画面
    ユーザ情報編集画面
    投稿一覧画面 (FAILED - 109)
    投稿詳細画面 (FAILED - 110)
    投稿編集画面 (FAILED - 111)
  他人の画面のテスト
    他人の投稿詳細画面のテスト
      表示内容の確認
        URLが正しい (FAILED - 112)
        「Book detail」と表示される (FAILED - 113)
        ユーザ画像・名前のリンク先が正しい (FAILED - 114)
        投稿のtitleが表示される (FAILED - 115)
        投稿のopinionが表示される (FAILED - 116)
        投稿の編集リンクが表示されない (FAILED - 117)
        投稿の削除リンクが表示されない (FAILED - 118)
      サイドバーの確認
        他人の名前と紹介文が表示される (FAILED - 119)
        他人のユーザ編集画面へのリンクが存在する (FAILED - 120)
        自分の名前と紹介文は表示されない (FAILED - 121)
        自分のユーザ編集画面へのリンクは存在しない (FAILED - 122)
    他人の投稿編集画面
      遷移できず、投稿一覧画面にリダイレクトされる (FAILED - 123)
    他人のユーザ詳細画面のテスト
      表示の確認
        URLが正しい (FAILED - 124)
        投稿一覧のユーザ画像のリンク先が正しい (FAILED - 125)
        投稿一覧に他人の投稿のtitleが表示され、リンクが正しい (FAILED - 126)
        投稿一覧に他人の投稿のopinionが表示される (FAILED - 127)
        自分の投稿は表示されない (FAILED - 128)
      サイドバーの確認
        他人の名前と紹介文が表示される (FAILED - 129)
        他人のユーザ編集画面へのリンクが存在する (FAILED - 130)
        自分の名前と紹介文は表示されない (FAILED - 131)
        自分のユーザ編集画面へのリンクは存在しない (FAILED - 132)
    他人のユーザ情報編集画面
      遷移できず、自分のユーザ詳細画面にリダイレクトされる (FAILED - 133)
  グリッドシステムのテスト: container, row, col-md-〇を正しく使えている
    ユーザ一覧画面 (FAILED - 134)
    ユーザ詳細画面 (FAILED - 135)
    投稿一覧画面 (FAILED - 136)
    投稿詳細画面 (FAILED - 137)
  アイコンのテスト
    トップ画面
      本のアイコンが表示される
    アバウト画面
      本のアイコンが表示される (FAILED - 138)
    ヘッダー: ログインしていない場合
      Homeリンクのアイコンが表示される
      Aboutリンクのアイコンが表示される
      sign upリンクのアイコンが表示される
      loginリンクのアイコンが表示される
    ヘッダー: ログインしている場合
      Homeリンクのアイコンが表示される (FAILED - 139)
      Usersリンクのアイコンが表示される (FAILED - 140)
      Booksリンクのアイコンが表示される (FAILED - 141)
      log outリンクのアイコンが表示される (FAILED - 142)
    サイドバー
      ユーザ一覧画面でレンチアイコンが表示される (FAILED - 143)
      ユーザ詳細画面でレンチアイコンが表示される (FAILED - 144)
      投稿一覧画面でレンチアイコンが表示される (FAILED - 145)
      投稿詳細画面でレンチアイコンが表示される (FAILED - 146)

Failures:

  1) Userモデルのテスト バリデーションのテスト nameカラム 一意性があること
     Failure/Error: is_expected.to eq false

       expected: false
            got: true

       (compared using ==)

       Diff:
       @@ -1 +1 @@
       -false
       +true
     # ./spec/models/user_spec.rb:33:in `block (4 levels) in <main>'

  2) [STEP1] ユーザログイン前のテスト アバウト画面のテスト 表示内容の確認 URLが正しい
     Failure/Error: visit '/home/about'

     ActionController::RoutingError:
       No route matches [GET] "/home/about"
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:38:in `call_app'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:26:in `block in call'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:26:in `call'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.4/lib/rails/engine.rb:524:in `call'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-test-1.1.0/lib/rack/test.rb:58:in `get'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/rack_test/browser.rb:72:in `process'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/rack_test/browser.rb:47:in `process_and_follow_redirects'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/rack_test/browser.rb:24:in `visit'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/rack_test/driver.rb:46:in `visit'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:278:in `visit'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
     # ./spec/system/01_before_login_spec.rb:34:in `block (3 levels) in <main>'

  3) [STEP1] ユーザログイン前のテスト ヘッダーのテスト: ログインしていない場合 リンクの内容を確認 Aboutを押すと、アバウト画面に遷移する
     Failure/Error: is_expected.to eq '/home/about'

       expected: "/home/about"
            got: "/homes/about"

       (compared using ==)
     # ./spec/system/01_before_login_spec.rb:85:in `block (4 levels) in <main>'

  4) [STEP1] ユーザログイン前のテスト ユーザログイン 表示内容の確認 nameフォームが表示される
     Failure/Error: expect(page).to have_field 'user[name]'
       expected to find field "user[name]" that is not disabled but there were no matches
     # ./spec/system/01_before_login_spec.rb:164:in `block (4 levels) in <main>'

  5) [STEP1] ユーザログイン前のテスト ユーザログイン 表示内容の確認 emailフォームは表示されない
     Failure/Error: expect(page).not_to have_field 'user[email]'
       expected not to find visible field "user[email]" that is not disabled, found 1 match: ""
     # ./spec/system/01_before_login_spec.rb:173:in `block (4 levels) in <main>'

  6) [STEP1] ユーザログイン前のテスト ユーザログイン ログイン成功のテスト ログイン後のリダイレクト先が、ログインしたユーザの詳細画面になっている
     Failure/Error: fill_in 'user[name]', with: user.name

     Capybara::ElementNotFound:
       Unable to find field "user[name]" that is not disabled
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
     # ./spec/system/01_before_login_spec.rb:179:in `block (4 levels) in <main>'

  7) [STEP1] ユーザログイン前のテスト ユーザログイン ログイン失敗のテスト ログインに失敗し、ログイン画面にリダイレクトされる
     Failure/Error: fill_in 'user[name]', with: ''

     Capybara::ElementNotFound:
       Unable to find field "user[name]" that is not disabled
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
     # ./spec/system/01_before_login_spec.rb:191:in `block (4 levels) in <main>'

  8) [STEP1] ユーザログイン前のテスト ヘッダーのテスト: ログインしている場合 ヘッダーの表示を確認 タイトルが表示される
     Failure/Error: fill_in 'user[name]', with: user.name

     Capybara::ElementNotFound:
       Unable to find field "user[name]" that is not disabled
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
     # ./spec/system/01_before_login_spec.rb:207:in `block (3 levels) in <main>'

  9) [STEP1] ユーザログイン前のテスト ヘッダーのテスト: ログインしている場合 ヘッダーの表示を確認 Homeリンクが表示される: 左上から1番目のリンクが「Home」である
     Failure/Error: fill_in 'user[name]', with: user.name

     Capybara::ElementNotFound:
       Unable to find field "user[name]" that is not disabled
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
     # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
     # ./spec/system/01_before_login_spec.rb:207:in `block (3 levels) in <main>'

  10) [STEP1] ユーザログイン前のテスト ヘッダーのテスト: ログインしている場合 ヘッダーの表示を確認 Usersリンクが表示される: 左上から2番目のリンクが「Users」である
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/01_before_login_spec.rb:207:in `block (3 levels) in <main>'

  11) [STEP1] ユーザログイン前のテスト ヘッダーのテスト: ログインしている場合 ヘッダーの表示を確認 Booksリンクが表示される: 左上から3番目のリンクが「Books」である
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/01_before_login_spec.rb:207:in `block (3 levels) in <main>'

  12) [STEP1] ユーザログイン前のテスト ヘッダーのテスト: ログインしている場合 ヘッダーの表示を確認 log outリンクが表示される: 左上から4番目のリンクが「logout」である
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/01_before_login_spec.rb:207:in `block (3 levels) in <main>'

  13) [STEP1] ユーザログイン前のテスト ユーザログアウトのテスト ログアウト機能のテスト 正しくログアウトできている: ログアウト後のリダイレクト先においてAbout画面へのリンクが存在する
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/01_before_login_spec.rb:240:in `block (3 levels) in <main>'

  14) [STEP1] ユーザログイン前のテスト ユーザログアウトのテスト ログアウト機能のテスト ログアウト後のリダイレクト先が、トップになっている
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/01_before_login_spec.rb:240:in `block (3 levels) in <main>'

  15) [STEP2] ユーザログイン後のテスト ヘッダーのテスト: ログインしている場合 リンクの内容を確認: ※logoutは『ユーザログアウトのテスト』でテスト済みになります。 Homeを押すと、自分のユーザ詳細画面に遷移する
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  16) [STEP2] ユーザログイン後のテスト ヘッダーのテスト: ログインしている場合 リンクの内容を確認: ※logoutは『ユーザログアウトのテスト』でテスト済みになります。 Usersを押すと、ユーザ一覧画面に遷移する
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  17) [STEP2] ユーザログイン後のテスト ヘッダーのテスト: ログインしている場合 リンクの内容を確認: ※logoutは『ユーザログアウトのテスト』でテスト済みになります。 Booksを押すと、投稿一覧画面に遷移する
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  18) [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト 表示内容の確認 URLが正しい
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  19) [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト 表示内容の確認 自分と他人の画像のリンク先が正しい
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  20) [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト 表示内容の確認 自分の投稿と他人の投稿のタイトルのリンク先がそれぞれ正しい
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  21) [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト 表示内容の確認 自分の投稿と他人の投稿のオピニオンが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  22) [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト サイドバーの確認 自分の名前と紹介文が表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  23) [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト サイドバーの確認 自分のユーザ編集画面へのリンクが存在する
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  24) [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト サイドバーの確認 「New book」と表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  25) [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト サイドバーの確認 titleフォームが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  26) [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト サイドバーの確認 titleフォームに値が入っていない
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  27) [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト サイドバーの確認 opinionフォームが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  28) [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト サイドバーの確認 opinionフォームに値が入っていない
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  29) [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト サイドバーの確認 Create Bookボタンが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  30) [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト 投稿成功のテスト 自分の新しい投稿が正しく保存される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  31) [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト 投稿成功のテスト リダイレクト先が、保存できた投稿の詳細画面になっている
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  32) [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 表示内容の確認 URLが正しい
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  33) [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 表示内容の確認 「Book detail」と表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  34) [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 表示内容の確認 ユーザ画像・名前のリンク先が正しい
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  35) [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 表示内容の確認 投稿のtitleが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  36) [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 表示内容の確認 投稿のopinionが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  37) [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 表示内容の確認 投稿の編集リンクが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  38) [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 表示内容の確認 投稿の削除リンクが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  39) [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト サイドバーの確認 自分の名前と紹介文が表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  40) [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト サイドバーの確認 自分のユーザ編集画面へのリンクが存在する
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  41) [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト サイドバーの確認 「New book」と表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  42) [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト サイドバーの確認 titleフォームが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  43) [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト サイドバーの確認 titleフォームに値が入っていない
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  44) [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト サイドバーの確認 opinionフォームが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  45) [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト サイドバーの確認 opinionフォームに値が入っていない
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  46) [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト サイドバーの確認 Create Bookボタンが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  47) [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 投稿成功のテスト 自分の新しい投稿が正しく保存される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  48) [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 編集リンクのテスト 編集画面に遷移する
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  49) [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 削除リンクのテスト 正しく削除される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  50) [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 削除リンクのテスト リダイレクト先が、投稿一覧画面になっている
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  51) [STEP2] ユーザログイン後のテスト 自分の投稿編集画面のテスト 表示の確認 URLが正しい
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  52) [STEP2] ユーザログイン後のテスト 自分の投稿編集画面のテスト 表示の確認 「Editing Book」と表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  53) [STEP2] ユーザログイン後のテスト 自分の投稿編集画面のテスト 表示の確認 title編集フォームが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  54) [STEP2] ユーザログイン後のテスト 自分の投稿編集画面のテスト 表示の確認 opinion編集フォームが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  55) [STEP2] ユーザログイン後のテスト 自分の投稿編集画面のテスト 表示の確認 Update Bookボタンが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  56) [STEP2] ユーザログイン後のテスト 自分の投稿編集画面のテスト 表示の確認 Showリンクが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  57) [STEP2] ユーザログイン後のテスト 自分の投稿編集画面のテスト 表示の確認 Backリンクが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  58) [STEP2] ユーザログイン後のテスト 自分の投稿編集画面のテスト 編集成功のテスト titleが正しく更新される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  59) [STEP2] ユーザログイン後のテスト 自分の投稿編集画面のテスト 編集成功のテスト bodyが正しく更新される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  60) [STEP2] ユーザログイン後のテスト 自分の投稿編集画面のテスト 編集成功のテスト リダイレクト先が、更新した投稿の詳細画面になっている
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  61) [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト 表示内容の確認 URLが正しい
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  62) [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト 表示内容の確認 自分と他人の画像が表示される: fallbackの画像がサイドバーの1つ＋一覧(2人)の2つの計3つ存在する
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  63) [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト 表示内容の確認 自分と他人の名前がそれぞれ表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  64) [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト 表示内容の確認 自分と他人のshowリンクがそれぞれ表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  65) [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト サイドバーの確認 自分の名前と紹介文が表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  66) [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト サイドバーの確認 自分のユーザ編集画面へのリンクが存在する
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  67) [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト サイドバーの確認 「New book」と表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  68) [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト サイドバーの確認 titleフォームが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  69) [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト サイドバーの確認 titleフォームに値が入っていない
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  70) [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト サイドバーの確認 opinionフォームが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  71) [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト サイドバーの確認 opinionフォームに値が入っていない
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  72) [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト サイドバーの確認 Create Bookボタンが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  73) [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト 表示の確認 URLが正しい
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  74) [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト 表示の確認 投稿一覧のユーザ画像のリンク先が正しい
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  75) [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト 表示の確認 投稿一覧に自分の投稿のtitleが表示され、リンクが正しい
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  76) [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト 表示の確認 投稿一覧に自分の投稿のopinionが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  77) [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト 表示の確認 他人の投稿は表示されない
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  78) [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト サイドバーの確認 自分の名前と紹介文が表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  79) [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト サイドバーの確認 自分のユーザ編集画面へのリンクが存在する
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  80) [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト サイドバーの確認 「New book」と表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  81) [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト サイドバーの確認 titleフォームが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  82) [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト サイドバーの確認 titleフォームに値が入っていない
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  83) [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト サイドバーの確認 opinionフォームが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  84) [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト サイドバーの確認 opinionフォームに値が入っていない
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  85) [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト サイドバーの確認 Create Bookボタンが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  86) [STEP2] ユーザログイン後のテスト 自分のユーザ情報編集画面のテスト 表示の確認 URLが正しい
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  87) [STEP2] ユーザログイン後のテスト 自分のユーザ情報編集画面のテスト 表示の確認 名前編集フォームに自分の名前が表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  88) [STEP2] ユーザログイン後のテスト 自分のユーザ情報編集画面のテスト 表示の確認 画像編集フォームが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  89) [STEP2] ユーザログイン後のテスト 自分のユーザ情報編集画面のテスト 表示の確認 自己紹介編集フォームに自分の自己紹介文が表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  90) [STEP2] ユーザログイン後のテスト 自分のユーザ情報編集画面のテスト 表示の確認 Update Userボタンが表示される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  91) [STEP2] ユーザログイン後のテスト 自分のユーザ情報編集画面のテスト 更新成功のテスト nameが正しく更新される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  92) [STEP2] ユーザログイン後のテスト 自分のユーザ情報編集画面のテスト 更新成功のテスト introductionが正しく更新される
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  93) [STEP2] ユーザログイン後のテスト 自分のユーザ情報編集画面のテスト 更新成功のテスト リダイレクト先が、自分のユーザ詳細画面になっている
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/02_after_login_spec.rb:11:in `block (2 levels) in <main>'

  94) [STEP3] 仕上げのテスト サクセスメッセージのテスト ユーザログイン成功時
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/03_finishing_touches_spec.rb:23:in `block (3 levels) in <main>'

  95) [STEP3] 仕上げのテスト サクセスメッセージのテスト ユーザログアウト成功時
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/03_finishing_touches_spec.rb:30:in `block (3 levels) in <main>'

  96) [STEP3] 仕上げのテスト サクセスメッセージのテスト ユーザのプロフィール情報更新成功時
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/03_finishing_touches_spec.rb:40:in `block (3 levels) in <main>'

  97) [STEP3] 仕上げのテスト サクセスメッセージのテスト 投稿データの新規投稿成功時: 投稿一覧画面から行います。
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/03_finishing_touches_spec.rb:49:in `block (3 levels) in <main>'

  98) [STEP3] 仕上げのテスト サクセスメッセージのテスト 投稿データの更新成功時
      Failure/Error: fill_in 'user[name]', with: user.name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/03_finishing_touches_spec.rb:60:in `block (3 levels) in <main>'

  99) [STEP3] 仕上げのテスト 処理失敗時のテスト ユーザのプロフィール情報編集失敗: nameを1文字にする 更新されない
      Failure/Error: fill_in 'user[name]', with: @user_old_name

      Capybara::ElementNotFound:
        Unable to find field "user[name]" that is not disabled
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
      # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
      # ./spec/system/03_finishing_touches_spec.rb:101:in `block (4 levels) in <main>'

  100) [STEP3] 仕上げのテスト 処理失敗時のテスト ユーザのプロフィール情報編集失敗: nameを1文字にする ユーザ編集画面を表示しており、フォームの内容が正しい
       Failure/Error: fill_in 'user[name]', with: @user_old_name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:101:in `block (4 levels) in <main>'

  101) [STEP3] 仕上げのテスト 処理失敗時のテスト ユーザのプロフィール情報編集失敗: nameを1文字にする バリデーションエラーが表示される
       Failure/Error: fill_in 'user[name]', with: @user_old_name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:101:in `block (4 levels) in <main>'

  102) [STEP3] 仕上げのテスト 処理失敗時のテスト 投稿データの新規投稿失敗: 投稿一覧画面から行い、titleを空にする 投稿が保存されない
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:123:in `block (4 levels) in <main>'

  103) [STEP3] 仕上げのテスト 処理失敗時のテスト 投稿データの新規投稿失敗: 投稿一覧画面から行い、titleを空にする 投稿一覧画面を表示している
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:123:in `block (4 levels) in <main>'

  104) [STEP3] 仕上げのテスト 処理失敗時のテスト 投稿データの新規投稿失敗: 投稿一覧画面から行い、titleを空にする 新規投稿フォームの内容が正しい
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:123:in `block (4 levels) in <main>'

  105) [STEP3] 仕上げのテスト 処理失敗時のテスト 投稿データの新規投稿失敗: 投稿一覧画面から行い、titleを空にする バリデーションエラーが表示される
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:123:in `block (4 levels) in <main>'

  106) [STEP3] 仕上げのテスト 処理失敗時のテスト 投稿データの更新失敗: titleを空にする 投稿が更新されない
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:153:in `block (4 levels) in <main>'

  107) [STEP3] 仕上げのテスト 処理失敗時のテスト 投稿データの更新失敗: titleを空にする 投稿編集画面を表示しており、フォームの内容が正しい
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:153:in `block (4 levels) in <main>'

  108) [STEP3] 仕上げのテスト 処理失敗時のテスト 投稿データの更新失敗: titleを空にする エラーメッセージが表示される
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:153:in `block (4 levels) in <main>'

  109) [STEP3] 仕上げのテスト ログインしていない場合のアクセス制限のテスト: アクセスできず、ログイン画面に遷移する 投稿一覧画面
       Failure/Error: <%= link_to edit_user_path(@user) do %>

       ActionView::Template::Error:
         No route matches {:action=>"edit", :controller=>"users", :id=>nil}, missing required keys: [:id]
       # ./app/views/users/_user_info.html.erb:6:in `_app_views_users__user_info_html_erb___458945683198013940_73803940'
       # ./app/views/books/index.html.erb:20:in `_app_views_books_index_html_erb___127124336405009877_98765720'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:38:in `call_app'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:26:in `block in call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:26:in `call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.4/lib/rails/engine.rb:524:in `call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-test-1.1.0/lib/rack/test.rb:58:in `get'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/rack_test/browser.rb:72:in `process'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/rack_test/browser.rb:47:in `process_and_follow_redirects'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/rack_test/browser.rb:24:in `visit'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/rack_test/driver.rb:46:in `visit'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:278:in `visit'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:192:in `block (3 levels) in <main>'
       # ------------------
       # --- Caused by: ---
       # ActionController::UrlGenerationError:
       #   No route matches {:action=>"edit", :controller=>"users", :id=>nil}, missing required keys: [:id]
       #   ./app/views/users/_user_info.html.erb:6:in `_app_views_users__user_info_html_erb___458945683198013940_73803940'

  110) [STEP3] 仕上げのテスト ログインしていない場合のアクセス制限のテスト: アクセスできず、ログイン画面に遷移する 投稿詳細画面
       Failure/Error: is_expected.to eq '/users/sign_in'

         expected: "/users/sign_in"
              got: "/books/1"

         (compared using ==)
       # ./spec/system/03_finishing_touches_spec.rb:197:in `block (3 levels) in <main>'

  111) [STEP3] 仕上げのテスト ログインしていない場合のアクセス制限のテスト: アクセスできず、ログイン画面に遷移する 投稿編集画面
       Failure/Error: is_expected.to eq '/users/sign_in'

         expected: "/users/sign_in"
              got: "/books/1/edit"

         (compared using ==)
       # ./spec/system/03_finishing_touches_spec.rb:201:in `block (3 levels) in <main>'

  112) [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト 表示内容の確認 URLが正しい
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  113) [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト 表示内容の確認 「Book detail」と表示される
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  114) [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト 表示内容の確認 ユーザ画像・名前のリンク先が正しい
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  115) [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト 表示内容の確認 投稿のtitleが表示される
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  116) [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト 表示内容の確認 投稿のopinionが表示される
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  117) [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト 表示内容の確認 投稿の編集リンクが表示されない
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  118) [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト 表示内容の確認 投稿の削除リンクが表示されない
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  119) [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト サイドバーの確認 他人の名前と紹介文が表示される
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  120) [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト サイドバーの確認 他人のユーザ編集画面へのリンクが存在する
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  121) [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト サイドバーの確認 自分の名前と紹介文は表示されない
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  122) [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト サイドバーの確認 自分のユーザ編集画面へのリンクは存在しない
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  123) [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿編集画面 遷移できず、投稿一覧画面にリダイレクトされる
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  124) [STEP3] 仕上げのテスト 他人の画面のテスト 他人のユーザ詳細画面のテスト 表示の確認 URLが正しい
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  125) [STEP3] 仕上げのテスト 他人の画面のテスト 他人のユーザ詳細画面のテスト 表示の確認 投稿一覧のユーザ画像のリンク先が正しい
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  126) [STEP3] 仕上げのテスト 他人の画面のテスト 他人のユーザ詳細画面のテスト 表示の確認 投稿一覧に他人の投稿のtitleが表示され、リンクが正しい
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  127) [STEP3] 仕上げのテスト 他人の画面のテスト 他人のユーザ詳細画面のテスト 表示の確認 投稿一覧に他人の投稿のopinionが表示される
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  128) [STEP3] 仕上げのテスト 他人の画面のテスト 他人のユーザ詳細画面のテスト 表示の確認 自分の投稿は表示されない
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  129) [STEP3] 仕上げのテスト 他人の画面のテスト 他人のユーザ詳細画面のテスト サイドバーの確認 他人の名前と紹介文が表示される
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  130) [STEP3] 仕上げのテスト 他人の画面のテスト 他人のユーザ詳細画面のテスト サイドバーの確認 他人のユーザ編集画面へのリンクが存在する
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  131) [STEP3] 仕上げのテスト 他人の画面のテスト 他人のユーザ詳細画面のテスト サイドバーの確認 自分の名前と紹介文は表示されない
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  132) [STEP3] 仕上げのテスト 他人の画面のテスト 他人のユーザ詳細画面のテスト サイドバーの確認 自分のユーザ編集画面へのリンクは存在しない
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  133) [STEP3] 仕上げのテスト 他人の画面のテスト 他人のユーザ情報編集画面 遷移できず、自分のユーザ詳細画面にリダイレクトされる
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:208:in `block (3 levels) in <main>'

  134) [STEP3] 仕上げのテスト グリッドシステムのテスト: container, row, col-md-〇を正しく使えている ユーザ一覧画面
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:322:in `block (3 levels) in <main>'

  135) [STEP3] 仕上げのテスト グリッドシステムのテスト: container, row, col-md-〇を正しく使えている ユーザ詳細画面
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:322:in `block (3 levels) in <main>'

  136) [STEP3] 仕上げのテスト グリッドシステムのテスト: container, row, col-md-〇を正しく使えている 投稿一覧画面
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:322:in `block (3 levels) in <main>'

  137) [STEP3] 仕上げのテスト グリッドシステムのテスト: container, row, col-md-〇を正しく使えている 投稿詳細画面
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:322:in `block (3 levels) in <main>'

  138) [STEP3] 仕上げのテスト アイコンのテスト アバウト画面 本のアイコンが表示される
       Failure/Error: visit '/home/about'

       ActionController::RoutingError:
         No route matches [GET] "/home/about"
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:38:in `call_app'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:26:in `block in call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:26:in `call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.4/lib/rails/engine.rb:524:in `call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/rack-test-1.1.0/lib/rack/test.rb:58:in `get'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/rack_test/browser.rb:72:in `process'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/rack_test/browser.rb:47:in `process_and_follow_redirects'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/rack_test/browser.rb:24:in `visit'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/rack_test/driver.rb:46:in `visit'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:278:in `visit'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:366:in `block (4 levels) in <main>'

  139) [STEP3] 仕上げのテスト アイコンのテスト ヘッダー: ログインしている場合 Homeリンクのアイコンが表示される
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:400:in `block (4 levels) in <main>'

  140) [STEP3] 仕上げのテスト アイコンのテスト ヘッダー: ログインしている場合 Usersリンクのアイコンが表示される
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:400:in `block (4 levels) in <main>'

  141) [STEP3] 仕上げのテスト アイコンのテスト ヘッダー: ログインしている場合 Booksリンクのアイコンが表示される
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:400:in `block (4 levels) in <main>'

  142) [STEP3] 仕上げのテスト アイコンのテスト ヘッダー: ログインしている場合 log outリンクのアイコンが表示される
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:400:in `block (4 levels) in <main>'

  143) [STEP3] 仕上げのテスト アイコンのテスト サイドバー ユーザ一覧画面でレンチアイコンが表示される
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:424:in `block (4 levels) in <main>'

  144) [STEP3] 仕上げのテスト アイコンのテスト サイドバー ユーザ詳細画面でレンチアイコンが表示される
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:424:in `block (4 levels) in <main>'

  145) [STEP3] 仕上げのテスト アイコンのテスト サイドバー 投稿一覧画面でレンチアイコンが表示される
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:424:in `block (4 levels) in <main>'

  146) [STEP3] 仕上げのテスト アイコンのテスト サイドバー 投稿詳細画面でレンチアイコンが表示される
       Failure/Error: fill_in 'user[name]', with: user.name

       Capybara::ElementNotFound:
         Unable to find field "user[name]" that is not disabled
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/base.rb:83:in `synchronize'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:292:in `synced_resolve'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/finders.rb:53:in `find'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/node/actions.rb:91:in `fill_in'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/session.rb:768:in `block (2 levels) in <class:Session>'
       # /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.34.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
       # ./spec/system/03_finishing_touches_spec.rb:424:in `block (4 levels) in <main>'

Finished in 8.63 seconds (files took 1.34 seconds to load)
197 examples, 146 failures

Failed examples:

rspec ./spec/models/user_spec.rb:31 # Userモデルのテスト バリデーションのテスト nameカラム 一意性があること
rspec ./spec/system/01_before_login_spec.rb:38 # [STEP1] ユーザログイン前のテスト アバウト画面のテスト 表示内容の確認 URLが正しい
rspec ./spec/system/01_before_login_spec.rb:81 # [STEP1] ユーザログイン前のテスト ヘッダーのテスト: ログインしていない場合 リンクの内容を確認 Aboutを押すと、アバウト画面に遷移する
rspec ./spec/system/01_before_login_spec.rb:163 # [STEP1] ユーザログイン前のテスト ユーザログイン 表示内容の確認 nameフォームが表示される
rspec ./spec/system/01_before_login_spec.rb:172 # [STEP1] ユーザログイン前のテスト ユーザログイン 表示内容の確認 emailフォームは表示されない
rspec ./spec/system/01_before_login_spec.rb:184 # [STEP1] ユーザログイン前のテスト ユーザログイン ログイン成功のテスト ログイン後のリダイレクト先が、ログインしたユーザの詳細画面になっている
rspec ./spec/system/01_before_login_spec.rb:196 # [STEP1] ユーザログイン前のテスト ユーザログイン ログイン失敗のテスト ログインに失敗し、ログイン画面にリダイレクトされる
rspec ./spec/system/01_before_login_spec.rb:213 # [STEP1] ユーザログイン前のテスト ヘッダーのテスト: ログインしている場合 ヘッダーの表示を確認 タイトルが表示される
rspec ./spec/system/01_before_login_spec.rb:216 # [STEP1] ユーザログイン前のテスト ヘッダーのテスト: ログインしている場合 ヘッダーの表示を確認 Homeリンクが表示される: 左上から1番目のリンクが「Home」である
rspec ./spec/system/01_before_login_spec.rb:220 # [STEP1] ユーザログイン前のテスト ヘッダーのテスト: ログインしている場合 ヘッダーの表示を確認 Usersリンクが表示される: 左上から2番目のリンクが「Users」である
rspec ./spec/system/01_before_login_spec.rb:224 # [STEP1] ユーザログイン前のテスト ヘッダーのテスト: ログインしている場合 ヘッダーの表示を確認 Booksリンクが表示される: 左上から3番目のリンクが「Books」である
rspec ./spec/system/01_before_login_spec.rb:228 # [STEP1] ユーザログイン前のテスト ヘッダーのテスト: ログインしている場合 ヘッダーの表示を確認 log outリンクが表示される: 左上から4番目のリンクが「logout」である
rspec ./spec/system/01_before_login_spec.rb:249 # [STEP1] ユーザログイン前のテスト ユーザログアウトのテスト ログアウト機能のテスト 正しくログアウトできている: ログアウト後のリダイレクト先においてAbout画面へのリンクが存在する
rspec ./spec/system/01_before_login_spec.rb:252 # [STEP1] ユーザログイン前のテスト ユーザログアウトのテスト ログアウト機能のテスト ログアウト後のリダイレクト先が、トップになっている
rspec ./spec/system/02_after_login_spec.rb:20 # [STEP2] ユーザログイン後のテスト ヘッダーのテスト: ログインしている場合 リンクの内容を確認: ※logoutは『ユーザログアウトのテスト』でテスト済みになります。 Homeを押すと、自分のユーザ詳細画面に遷移する
rspec ./spec/system/02_after_login_spec.rb:26 # [STEP2] ユーザログイン後のテスト ヘッダーのテスト: ログインしている場合 リンクの内容を確認: ※logoutは『ユーザログアウトのテスト』でテスト済みになります。 Usersを押すと、ユーザ一覧画面に遷移する
rspec ./spec/system/02_after_login_spec.rb:32 # [STEP2] ユーザログイン後のテスト ヘッダーのテスト: ログインしている場合 リンクの内容を確認: ※logoutは『ユーザログアウトのテスト』でテスト済みになります。 Booksを押すと、投稿一覧画面に遷移する
rspec ./spec/system/02_after_login_spec.rb:47 # [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト 表示内容の確認 URLが正しい
rspec ./spec/system/02_after_login_spec.rb:50 # [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト 表示内容の確認 自分と他人の画像のリンク先が正しい
rspec ./spec/system/02_after_login_spec.rb:54 # [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト 表示内容の確認 自分の投稿と他人の投稿のタイトルのリンク先がそれぞれ正しい
rspec ./spec/system/02_after_login_spec.rb:58 # [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト 表示内容の確認 自分の投稿と他人の投稿のオピニオンが表示される
rspec ./spec/system/02_after_login_spec.rb:65 # [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト サイドバーの確認 自分の名前と紹介文が表示される
rspec ./spec/system/02_after_login_spec.rb:69 # [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト サイドバーの確認 自分のユーザ編集画面へのリンクが存在する
rspec ./spec/system/02_after_login_spec.rb:72 # [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト サイドバーの確認 「New book」と表示される
rspec ./spec/system/02_after_login_spec.rb:75 # [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト サイドバーの確認 titleフォームが表示される
rspec ./spec/system/02_after_login_spec.rb:78 # [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト サイドバーの確認 titleフォームに値が入っていない
rspec ./spec/system/02_after_login_spec.rb:81 # [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト サイドバーの確認 opinionフォームが表示される
rspec ./spec/system/02_after_login_spec.rb:84 # [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト サイドバーの確認 opinionフォームに値が入っていない
rspec ./spec/system/02_after_login_spec.rb:87 # [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト サイドバーの確認 Create Bookボタンが表示される
rspec ./spec/system/02_after_login_spec.rb:98 # [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト 投稿成功のテスト 自分の新しい投稿が正しく保存される
rspec ./spec/system/02_after_login_spec.rb:101 # [STEP2] ユーザログイン後のテスト 投稿一覧画面のテスト 投稿成功のテスト リダイレクト先が、保存できた投稿の詳細画面になっている
rspec ./spec/system/02_after_login_spec.rb:114 # [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 表示内容の確認 URLが正しい
rspec ./spec/system/02_after_login_spec.rb:117 # [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 表示内容の確認 「Book detail」と表示される
rspec ./spec/system/02_after_login_spec.rb:120 # [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 表示内容の確認 ユーザ画像・名前のリンク先が正しい
rspec ./spec/system/02_after_login_spec.rb:123 # [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 表示内容の確認 投稿のtitleが表示される
rspec ./spec/system/02_after_login_spec.rb:126 # [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 表示内容の確認 投稿のopinionが表示される
rspec ./spec/system/02_after_login_spec.rb:129 # [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 表示内容の確認 投稿の編集リンクが表示される
rspec ./spec/system/02_after_login_spec.rb:132 # [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 表示内容の確認 投稿の削除リンクが表示される
rspec ./spec/system/02_after_login_spec.rb:138 # [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト サイドバーの確認 自分の名前と紹介文が表示される
rspec ./spec/system/02_after_login_spec.rb:142 # [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト サイドバーの確認 自分のユーザ編集画面へのリンクが存在する
rspec ./spec/system/02_after_login_spec.rb:145 # [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト サイドバーの確認 「New book」と表示される
rspec ./spec/system/02_after_login_spec.rb:148 # [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト サイドバーの確認 titleフォームが表示される
rspec ./spec/system/02_after_login_spec.rb:151 # [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト サイドバーの確認 titleフォームに値が入っていない
rspec ./spec/system/02_after_login_spec.rb:154 # [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト サイドバーの確認 opinionフォームが表示される
rspec ./spec/system/02_after_login_spec.rb:157 # [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト サイドバーの確認 opinionフォームに値が入っていない
rspec ./spec/system/02_after_login_spec.rb:160 # [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト サイドバーの確認 Create Bookボタンが表示される
rspec ./spec/system/02_after_login_spec.rb:171 # [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 投稿成功のテスト 自分の新しい投稿が正しく保存される
rspec ./spec/system/02_after_login_spec.rb:177 # [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 編集リンクのテスト 編集画面に遷移する
rspec ./spec/system/02_after_login_spec.rb:188 # [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 削除リンクのテスト 正しく削除される
rspec ./spec/system/02_after_login_spec.rb:191 # [STEP2] ユーザログイン後のテスト 自分の投稿詳細画面のテスト 削除リンクのテスト リダイレクト先が、投稿一覧画面になっている
rspec ./spec/system/02_after_login_spec.rb:203 # [STEP2] ユーザログイン後のテスト 自分の投稿編集画面のテスト 表示の確認 URLが正しい
rspec ./spec/system/02_after_login_spec.rb:206 # [STEP2] ユーザログイン後のテスト 自分の投稿編集画面のテスト 表示の確認 「Editing Book」と表示される
rspec ./spec/system/02_after_login_spec.rb:209 # [STEP2] ユーザログイン後のテスト 自分の投稿編集画面のテスト 表示の確認 title編集フォームが表示される
rspec ./spec/system/02_after_login_spec.rb:212 # [STEP2] ユーザログイン後のテスト 自分の投稿編集画面のテスト 表示の確認 opinion編集フォームが表示される
rspec ./spec/system/02_after_login_spec.rb:215 # [STEP2] ユーザログイン後のテスト 自分の投稿編集画面のテスト 表示の確認 Update Bookボタンが表示される
rspec ./spec/system/02_after_login_spec.rb:218 # [STEP2] ユーザログイン後のテスト 自分の投稿編集画面のテスト 表示の確認 Showリンクが表示される
rspec ./spec/system/02_after_login_spec.rb:221 # [STEP2] ユーザログイン後のテスト 自分の投稿編集画面のテスト 表示の確認 Backリンクが表示される
rspec ./spec/system/02_after_login_spec.rb:235 # [STEP2] ユーザログイン後のテスト 自分の投稿編集画面のテスト 編集成功のテスト titleが正しく更新される
rspec ./spec/system/02_after_login_spec.rb:238 # [STEP2] ユーザログイン後のテスト 自分の投稿編集画面のテスト 編集成功のテスト bodyが正しく更新される
rspec ./spec/system/02_after_login_spec.rb:241 # [STEP2] ユーザログイン後のテスト 自分の投稿編集画面のテスト 編集成功のテスト リダイレクト先が、更新した投稿の詳細画面になっている
rspec ./spec/system/02_after_login_spec.rb:254 # [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト 表示内容の確認 URLが正しい
rspec ./spec/system/02_after_login_spec.rb:257 # [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト 表示内容の確認 自分と他人の画像が表示される: fallbackの画像がサイドバーの1つ＋一覧(2人)の2つの計3つ存在する
rspec ./spec/system/02_after_login_spec.rb:260 # [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト 表示内容の確認 自分と他人の名前がそれぞれ表示される
rspec ./spec/system/02_after_login_spec.rb:264 # [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト 表示内容の確認 自分と他人のshowリンクがそれぞれ表示される
rspec ./spec/system/02_after_login_spec.rb:271 # [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト サイドバーの確認 自分の名前と紹介文が表示される
rspec ./spec/system/02_after_login_spec.rb:275 # [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト サイドバーの確認 自分のユーザ編集画面へのリンクが存在する
rspec ./spec/system/02_after_login_spec.rb:278 # [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト サイドバーの確認 「New book」と表示される
rspec ./spec/system/02_after_login_spec.rb:281 # [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト サイドバーの確認 titleフォームが表示される
rspec ./spec/system/02_after_login_spec.rb:284 # [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト サイドバーの確認 titleフォームに値が入っていない
rspec ./spec/system/02_after_login_spec.rb:287 # [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト サイドバーの確認 opinionフォームが表示される
rspec ./spec/system/02_after_login_spec.rb:290 # [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト サイドバーの確認 opinionフォームに値が入っていない
rspec ./spec/system/02_after_login_spec.rb:293 # [STEP2] ユーザログイン後のテスト ユーザ一覧画面のテスト サイドバーの確認 Create Bookボタンが表示される
rspec ./spec/system/02_after_login_spec.rb:305 # [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト 表示の確認 URLが正しい
rspec ./spec/system/02_after_login_spec.rb:308 # [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト 表示の確認 投稿一覧のユーザ画像のリンク先が正しい
rspec ./spec/system/02_after_login_spec.rb:311 # [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト 表示の確認 投稿一覧に自分の投稿のtitleが表示され、リンクが正しい
rspec ./spec/system/02_after_login_spec.rb:314 # [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト 表示の確認 投稿一覧に自分の投稿のopinionが表示される
rspec ./spec/system/02_after_login_spec.rb:317 # [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト 表示の確認 他人の投稿は表示されない
rspec ./spec/system/02_after_login_spec.rb:325 # [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト サイドバーの確認 自分の名前と紹介文が表示される
rspec ./spec/system/02_after_login_spec.rb:329 # [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト サイドバーの確認 自分のユーザ編集画面へのリンクが存在する
rspec ./spec/system/02_after_login_spec.rb:332 # [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト サイドバーの確認 「New book」と表示される
rspec ./spec/system/02_after_login_spec.rb:335 # [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト サイドバーの確認 titleフォームが表示される
rspec ./spec/system/02_after_login_spec.rb:338 # [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト サイドバーの確認 titleフォームに値が入っていない
rspec ./spec/system/02_after_login_spec.rb:341 # [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト サイドバーの確認 opinionフォームが表示される
rspec ./spec/system/02_after_login_spec.rb:344 # [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト サイドバーの確認 opinionフォームに値が入っていない
rspec ./spec/system/02_after_login_spec.rb:347 # [STEP2] ユーザログイン後のテスト 自分のユーザ詳細画面のテスト サイドバーの確認 Create Bookボタンが表示される
rspec ./spec/system/02_after_login_spec.rb:359 # [STEP2] ユーザログイン後のテスト 自分のユーザ情報編集画面のテスト 表示の確認 URLが正しい
rspec ./spec/system/02_after_login_spec.rb:362 # [STEP2] ユーザログイン後のテスト 自分のユーザ情報編集画面のテスト 表示の確認 名前編集フォームに自分の名前が表示される
rspec ./spec/system/02_after_login_spec.rb:365 # [STEP2] ユーザログイン後のテスト 自分のユーザ情報編集画面のテスト 表示の確認 画像編集フォームが表示される
rspec ./spec/system/02_after_login_spec.rb:368 # [STEP2] ユーザログイン後のテスト 自分のユーザ情報編集画面のテスト 表示の確認 自己紹介編集フォームに自分の自己紹介文が表示される
rspec ./spec/system/02_after_login_spec.rb:371 # [STEP2] ユーザログイン後のテスト 自分のユーザ情報編集画面のテスト 表示の確認 Update Userボタンが表示される
rspec ./spec/system/02_after_login_spec.rb:385 # [STEP2] ユーザログイン後のテスト 自分のユーザ情報編集画面のテスト 更新成功のテスト nameが正しく更新される
rspec ./spec/system/02_after_login_spec.rb:388 # [STEP2] ユーザログイン後のテスト 自分のユーザ情報編集画面のテスト 更新成功のテスト introductionが正しく更新される
rspec ./spec/system/02_after_login_spec.rb:391 # [STEP2] ユーザログイン後のテスト 自分のユーザ情報編集画面のテスト 更新成功のテスト リダイレクト先が、自分のユーザ詳細画面になっている
rspec ./spec/system/03_finishing_touches_spec.rb:21 # [STEP3] 仕上げのテスト サクセスメッセージのテスト ユーザログイン成功時
rspec ./spec/system/03_finishing_touches_spec.rb:28 # [STEP3] 仕上げのテスト サクセスメッセージのテスト ユーザログアウト成功時
rspec ./spec/system/03_finishing_touches_spec.rb:38 # [STEP3] 仕上げのテスト サクセスメッセージのテスト ユーザのプロフィール情報更新成功時
rspec ./spec/system/03_finishing_touches_spec.rb:47 # [STEP3] 仕上げのテスト サクセスメッセージのテスト 投稿データの新規投稿成功時: 投稿一覧画面から行います。
rspec ./spec/system/03_finishing_touches_spec.rb:58 # [STEP3] 仕上げのテスト サクセスメッセージのテスト 投稿データの更新成功時
rspec ./spec/system/03_finishing_touches_spec.rb:109 # [STEP3] 仕上げのテスト 処理失敗時のテスト ユーザのプロフィール情報編集失敗: nameを1文字にする 更新されない
rspec ./spec/system/03_finishing_touches_spec.rb:112 # [STEP3] 仕上げのテスト 処理失敗時のテスト ユーザのプロフィール情報編集失敗: nameを1文字にする ユーザ編集画面を表示しており、フォームの内容が正しい
rspec ./spec/system/03_finishing_touches_spec.rb:115 # [STEP3] 仕上げのテスト 処理失敗時のテスト ユーザのプロフィール情報編集失敗: nameを1文字にする バリデーションエラーが表示される
rspec ./spec/system/03_finishing_touches_spec.rb:131 # [STEP3] 仕上げのテスト 処理失敗時のテスト 投稿データの新規投稿失敗: 投稿一覧画面から行い、titleを空にする 投稿が保存されない
rspec ./spec/system/03_finishing_touches_spec.rb:134 # [STEP3] 仕上げのテスト 処理失敗時のテスト 投稿データの新規投稿失敗: 投稿一覧画面から行い、titleを空にする 投稿一覧画面を表示している
rspec ./spec/system/03_finishing_touches_spec.rb:140 # [STEP3] 仕上げのテスト 処理失敗時のテスト 投稿データの新規投稿失敗: 投稿一覧画面から行い、titleを空にする 新規投稿フォームの内容が正しい
rspec ./spec/system/03_finishing_touches_spec.rb:144 # [STEP3] 仕上げのテスト 処理失敗時のテスト 投稿データの新規投稿失敗: 投稿一覧画面から行い、titleを空にする バリデーションエラーが表示される
rspec ./spec/system/03_finishing_touches_spec.rb:162 # [STEP3] 仕上げのテスト 処理失敗時のテスト 投稿データの更新失敗: titleを空にする 投稿が更新されない
rspec ./spec/system/03_finishing_touches_spec.rb:165 # [STEP3] 仕上げのテスト 処理失敗時のテスト 投稿データの更新失敗: titleを空にする 投稿編集画面を表示しており、フォームの内容が正しい
rspec ./spec/system/03_finishing_touches_spec.rb:170 # [STEP3] 仕上げのテスト 処理失敗時のテスト 投稿データの更新失敗: titleを空にする エラーメッセージが表示される
rspec ./spec/system/03_finishing_touches_spec.rb:191 # [STEP3] 仕上げのテスト ログインしていない場合のアクセス制限のテスト: アクセスできず、ログイン画面に遷移する 投稿一覧画面
rspec ./spec/system/03_finishing_touches_spec.rb:195 # [STEP3] 仕上げのテスト ログインしていない場合のアクセス制限のテスト: アクセスできず、ログイン画面に遷移する 投稿詳細画面
rspec ./spec/system/03_finishing_touches_spec.rb:199 # [STEP3] 仕上げのテスト ログインしていない場合のアクセス制限のテスト: アクセスできず、ログイン画面に遷移する 投稿編集画面
rspec ./spec/system/03_finishing_touches_spec.rb:219 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト 表示内容の確認 URLが正しい
rspec ./spec/system/03_finishing_touches_spec.rb:222 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト 表示内容の確認 「Book detail」と表示される
rspec ./spec/system/03_finishing_touches_spec.rb:225 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト 表示内容の確認 ユーザ画像・名前のリンク先が正しい
rspec ./spec/system/03_finishing_touches_spec.rb:228 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト 表示内容の確認 投稿のtitleが表示される
rspec ./spec/system/03_finishing_touches_spec.rb:231 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト 表示内容の確認 投稿のopinionが表示される
rspec ./spec/system/03_finishing_touches_spec.rb:234 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト 表示内容の確認 投稿の編集リンクが表示されない
rspec ./spec/system/03_finishing_touches_spec.rb:237 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト 表示内容の確認 投稿の削除リンクが表示されない
rspec ./spec/system/03_finishing_touches_spec.rb:243 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト サイドバーの確認 他人の名前と紹介文が表示される
rspec ./spec/system/03_finishing_touches_spec.rb:247 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト サイドバーの確認 他人のユーザ編集画面へのリンクが存在する
rspec ./spec/system/03_finishing_touches_spec.rb:250 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト サイドバーの確認 自分の名前と紹介文は表示されない
rspec ./spec/system/03_finishing_touches_spec.rb:254 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿詳細画面のテスト サイドバーの確認 自分のユーザ編集画面へのリンクは存在しない
rspec ./spec/system/03_finishing_touches_spec.rb:261 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人の投稿編集画面 遷移できず、投稿一覧画面にリダイレクトされる
rspec ./spec/system/03_finishing_touches_spec.rb:273 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人のユーザ詳細画面のテスト 表示の確認 URLが正しい
rspec ./spec/system/03_finishing_touches_spec.rb:276 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人のユーザ詳細画面のテスト 表示の確認 投稿一覧のユーザ画像のリンク先が正しい
rspec ./spec/system/03_finishing_touches_spec.rb:279 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人のユーザ詳細画面のテスト 表示の確認 投稿一覧に他人の投稿のtitleが表示され、リンクが正しい
rspec ./spec/system/03_finishing_touches_spec.rb:282 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人のユーザ詳細画面のテスト 表示の確認 投稿一覧に他人の投稿のopinionが表示される
rspec ./spec/system/03_finishing_touches_spec.rb:285 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人のユーザ詳細画面のテスト 表示の確認 自分の投稿は表示されない
rspec ./spec/system/03_finishing_touches_spec.rb:292 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人のユーザ詳細画面のテスト サイドバーの確認 他人の名前と紹介文が表示される
rspec ./spec/system/03_finishing_touches_spec.rb:296 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人のユーザ詳細画面のテスト サイドバーの確認 他人のユーザ編集画面へのリンクが存在する
rspec ./spec/system/03_finishing_touches_spec.rb:299 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人のユーザ詳細画面のテスト サイドバーの確認 自分の名前と紹介文は表示されない
rspec ./spec/system/03_finishing_touches_spec.rb:303 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人のユーザ詳細画面のテスト サイドバーの確認 自分のユーザ編集画面へのリンクは存在しない
rspec ./spec/system/03_finishing_touches_spec.rb:310 # [STEP3] 仕上げのテスト 他人の画面のテスト 他人のユーザ情報編集画面 遷移できず、自分のユーザ詳細画面にリダイレクトされる
rspec ./spec/system/03_finishing_touches_spec.rb:327 # [STEP3] 仕上げのテスト グリッドシステムのテスト: container, row, col-md-〇を正しく使えている ユーザ一覧画面
rspec ./spec/system/03_finishing_touches_spec.rb:332 # [STEP3] 仕上げのテスト グリッドシステムのテスト: container, row, col-md-〇を正しく使えている ユーザ詳細画面
rspec ./spec/system/03_finishing_touches_spec.rb:337 # [STEP3] 仕上げのテスト グリッドシステムのテスト: container, row, col-md-〇を正しく使えている 投稿一覧画面
rspec ./spec/system/03_finishing_touches_spec.rb:342 # [STEP3] 仕上げのテスト グリッドシステムのテスト: container, row, col-md-〇を正しく使えている 投稿詳細画面
rspec ./spec/system/03_finishing_touches_spec.rb:369 # [STEP3] 仕上げのテスト アイコンのテスト アバウト画面 本のアイコンが表示される
rspec ./spec/system/03_finishing_touches_spec.rb:405 # [STEP3] 仕上げのテスト アイコンのテスト ヘッダー: ログインしている場合 Homeリンクのアイコンが表示される
rspec ./spec/system/03_finishing_touches_spec.rb:408 # [STEP3] 仕上げのテスト アイコンのテスト ヘッダー: ログインしている場合 Usersリンクのアイコンが表示される
rspec ./spec/system/03_finishing_touches_spec.rb:411 # [STEP3] 仕上げのテスト アイコンのテスト ヘッダー: ログインしている場合 Booksリンクのアイコンが表示される
rspec ./spec/system/03_finishing_touches_spec.rb:414 # [STEP3] 仕上げのテスト アイコンのテスト ヘッダー: ログインしている場合 log outリンクのアイコンが表示される
rspec ./spec/system/03_finishing_touches_spec.rb:429 # [STEP3] 仕上げのテスト アイコンのテスト サイドバー ユーザ一覧画面でレンチアイコンが表示される
rspec ./spec/system/03_finishing_touches_spec.rb:433 # [STEP3] 仕上げのテスト アイコンのテスト サイドバー ユーザ詳細画面でレンチアイコンが表示される
rspec ./spec/system/03_finishing_touches_spec.rb:437 # [STEP3] 仕上げのテスト アイコンのテスト サイドバー 投稿一覧画面でレンチアイコンが表示される
rspec ./spec/system/03_finishing_touches_spec.rb:441 # [STEP3] 仕上げのテスト アイコンのテスト サイドバー 投稿詳細画面でレンチアイコンが表示される

